### ISSUE TITLE
Silence "chown" output

### ISSUE THREAD

**Issue by Camo30** [AnotherStranger/docker-borg-backup#117]
Hello,

Thanks for building this docker image. I highly appreciate it.

I'm using it together with a network share and everything is working flawlessly but because the network share is build using fuse it does not allow to change permissions. Because of this all `chown` commands are failing with "permission denied" and are in my case actually unnecessary because the permissions are fine.

Could you silence the output of all `chown` commands or maybe integrate an environment variable to do so?

**Comment by AnotherStranger** [comment]
I will have a look. Is the container startup failing in your scenario?

**Comment by AnotherStranger** [comment]
Hey @Camo30,
I implemented an ENV-Flag to deactivate the chown functionality.
You can test the container by pulling 
```bash
docker pull ghcr.io/anotherstranger/borg-server:feature-silence-chown-output
```
You just have to set `ENUSURE_BACKUP_PERMISSIONS` to `false`.
Please let me know if this resolves your issue, and I will happily create a new release.

**Comment by Camo30** [comment]
Hello @AnotherStranger,

Many thanks! No, my container is not failing, everything works without any flaws. Just the log was flooded with "permission denied" errors but the permissions are fine.

**Comment by Camo30** [comment]
Hello @AnotherStranger,

I had the chance to test it out and it works perfectly - I tested both possibilities. Thank you very much!
